### ISSUE TITLE
 run_521d.py not working

### ISSUE THREAD

**Issue by amitabhs30** [knauth/goodix-521d-explanation#10]
this is the output:

#######################################################
This program might break your device.
Consider that it may flash the device firmware.
Continue at your own risk.
But don't hold us responsible if your device is broken!
Don't run this program as part of a regular process.
#######################################################
Type 2884 to continue and confirm that you are not a bot: 2884
__init__(21021, <class 'protocol.USBProtocol'>, 5)
Found Goodix device: "FingerPrint" from "Goodix" on bus 3 address 4.
Found interface data: 0
Found endpoint in: 0x83
Found endpoint out: 0x1
empty_buffer()
nop()
firmware_version()
Firmware: GFUSB_GM168SEC_APP_10019
preset_psk_read(3137470465, 32, 0)
Valid PSK: True
reset(True, False, 20)
read_sensor_register(0, 4)
read_otp()
Traceback (most recent call last):
  File "/home/amitabhs/personal/goodix-521d-explanation/goodix-fp-dump/run_521d.py", line 3, in <module>
    driver_52xd.main(0x521d)
  File "/home/amitabhs/personal/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 351, in main
    run_driver(device)
  File "/home/amitabhs/personal/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 134, in run_driver
    raise ValueError("Invalid OTP")
ValueError: Invalid OTP

**Comment by barsikus007** [comment]
same here, suppressing checking leads to random fingerprint scan results

**Comment by DanielCr2020** [comment]
I have this issue as well (kubuntu). When I look at `journalctl -u fprintd`, I get `fprintd[21702]: Device reported an error during identify for enroll: Invalid preset PSK read reply length: 41`. I also get `MCU has no config` as well in journalctl. 

My OTP is `b''`. When I try commenting out the check, the script runs, but I still get the same errors.

When I look at the .pgm files created in goodix-fp-dump, it seems that the fingerprint scanner is actually reading my finger when I try to flash.

But I still get those unknown errors.
