### ISSUE TITLE
run_521d.py not working

### ISSUE THREAD

**Issue by GregorioCavulla** [knauth/goodix-521d-explanation#7]
**Issue:**
1. **First run of the py script:**

[ghigo@EndeavourOSghigo goodix-fp-dump]$ sudo python run_521d.py 
Traceback (most recent call last):
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/run_521d.py", line 1, in <module>
    from driver_52xd import main
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 9, in <module>
    from goodix import FLAGS_TRANSPORT_LAYER_SECURITY_DATA, Device
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/goodix.py", line 6, in <module>
    from usb.core import USBTimeoutError
ModuleNotFoundError: No module named 'usb'

2. **Trying the suggested fix:**

[ghigo@EndeavourOSghigo goodix-fp-dump]$ cd ..
[ghigo@EndeavourOSghigo goodix-521d-explanation]$ ls
goodix-fp-dump  readme.md  usbreset
[ghigo@EndeavourOSghigo goodix-521d-explanation]$ cd usbreset/
[ghigo@EndeavourOSghigo usbreset]$ ls
usbreset.c
[ghigo@EndeavourOSghigo usbreset]$ gcc usbreset.c -o usbreset.out
[ghigo@EndeavourOSghigo usbreset]$ lsusb | grep FingerPrint
Bus 001 Device 003: ID 27c6:538d Shenzhen Goodix Technology Co.,Ltd. FingerPrint
[ghigo@EndeavourOSghigo usbreset]$ sudo ./usbreset.out /dev/bus/usb/001/003
Resetting USB device /dev/bus/usb/001/003
Reset successful

3. **Going for the python script again:**

[ghigo@EndeavourOSghigo usbreset]$ cd ..
[ghigo@EndeavourOSghigo goodix-521d-explanation]$ ls
goodix-fp-dump  readme.md  usbreset
[ghigo@EndeavourOSghigo goodix-521d-explanation]$ cd goodix-fp-dump/
[ghigo@EndeavourOSghigo goodix-fp-dump]$ sudo python run_521d.py 
Traceback (most recent call last):
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/run_521d.py", line 1, in <module>
    from driver_52xd import main
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/driver_52xd.py", line 9, in <module>
    from goodix import FLAGS_TRANSPORT_LAYER_SECURITY_DATA, Device
  File "/home/ghigo/Scrivania/goodix-521d-explanation/goodix-fp-dump/goodix.py", line 6, in <module>
    from usb.core import USBTimeoutError
ModuleNotFoundError: No module named 'usb'

tried several times, still not working

**Comment by ChenfaZheng** [comment]
run `sudo pacman -S python-pyusb` to install the module

**Comment by markreading** [comment]
Still having this error.  Installing python-pyusb didn't work for me either.   Any other suggestions?
